### ISSUE TITLE
Returning object instead of List

### ISSUE THREAD

**Issue by Buyani-Palota** [umbraco/Umbraco.Heartcore.Issues#118]
### Issue description

For query like this where I just want to return a single object:query ProductCategory($categoryName: String!, $parentCategoryCode: String!,$categoryCode: String!) {
  allCategory(where: { 
    AND: [
      { categoryName_contains: $categoryName },
      { parentCategoryCode_contains: $parentCategoryCode },
      {categoryCode_contains:$categoryCode}
    ]
  }) {
    items {
      categoryCode
    }
  }
}

Can this be included as a feature.

**Comment by jmf-umbraco** [comment]
Hi @Buyani-Palota, thanks for your suggestion!

Unfortunately the GraphQL specification doesn't allow us to return different types from a single query. Additionally, there is no guarantee that your `where` filter will only return a single item.

Hope that makes sense! Since we have no plan to implement this, I'm going to close off this issue for now.
