### ISSUE TITLE
Update HAL explorer

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Heartcore.Issues#119]
### Issue description

I had a look at an Umbraco Heartcore trial and noticed it seems to embed HAL explorer in backoffice:
https://github.com/toedter/hal-explorer

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/2919859/ffe1e691-ea31-45e7-95a5-b1347bd5152e)

Would it be possible to update/upgrade to a more modern version? The current seems to be build on Bootstrap 2 based on the class names in the iframe etc.

If it is the linked project used, it seems a bit more modern and perhaps possible to customize the UI a bit further?

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/2919859/21fce02c-e312-44a4-b9f9-ba1f36c0b0d7)

**Comment by jmf-umbraco** [comment]
Hi @bjarnef, thanks for your suggestion!

We're actually using [HAL Browser](https://github.com/mikekelly/hal-browser) under the hood, which unfortunately has no direct upgrade path.

Additionally, we have a plan to make some significant updates to our Heartcore APIs to bring them in line with core CMS APIs. The new incarnations of these APIs will have full OpenAPI / Swagger UI support and as such the HAL explorer is likely to become redundant.

Since we don't plan to work on this in the near future, we're going to close this issue for now.
