### ISSUE TITLE
Child list - order by Is Published not working

### ISSUE THREAD

**Issue by PMendesWebDev** [umbraco/Umbraco.Heartcore.Issues#123]
### Summary

The ordering by "Is Published" column is not working.

In the attached image, you can clearly see that Published and Unpublished are mixed up.

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/34547655/82b827be-7819-469c-b0bd-2c8da8f0febf)

### Steps to reproduce

Enable list view;
Add Is Published to columns;
Automatically order by "Is Published" (optional)

### Expected result

The nodes would be ordered from true to false or vice-versa.

### Actual result

All is mixed up

**Comment by jmf-umbraco** [comment]
Hi @PMendesWebDev.

Firstly, a big thank you for raising this issue. Every piece of feedback we receive helps us to make Umbraco better.

We really appreciate your patience while we wait for our team to have a look at this but we wanted to let you know that we see this and share with you the plan for what comes next.

- We'll replicate the issue to ensure that the problem is as described.
- We'll decide whether the behavior is an issue or if the behavior is intended.
- If we need any further information, we'll reach out with any questions.

**Comment by jmf-umbraco** [comment]
We are happy to inform you that we are currently in the process of updating our dependency on the core CMS, in which this issue has been resolved.

We will be rolling out this dependency upgrade for new Heartcore sites in either December or January, whereas existing sites will get it slightly later - most likely before end of Q1 2024.

We'll update this issue once the fix is live on all sites.

**Comment by jmf-umbraco** [comment]
We've just rolled out a version of Heartcore that fixes this issue for all sites created after 12th February 2024. Existing sites will have this rolled out in Q2 this year.
