### ISSUE TITLE
Mandatory validation of conditionally shown field not working

### ISSUE THREAD

**Issue by PascalIcatt** [umbraco/Umbraco.Heartcore.Issues#16]
### Issue description

When I create a form with 3 fields in Umbraco Forms in Heartcore:

1. Data Consent
2. Question1: Multiple Choice |  Yes/No | Mandatory
3. Question2: Short answer | Mandatory | Conditions: **Show** this field if **all** of the following match: Question1 is Yes Validation: Validate as an emailaddress

See attached the complete form json
[exampleFormJson.txt](https://github.com/umbraco/Umbraco.Cloud.Issues/files/7091399/exampleFormJson.txt)

When I send the following json as a post to /entries:
```
{
    "dataConsent": "on",
    "question1":"Yes",
    "question2":""
}
```
I get a 202 Accepted and the result is saved into the entries.

When I send the following json as a post to /entries:
```
{
    "dataConsent": "on",
    "question1":"Yes",
    "question2":"not-a-valid-emailaddress"
}
```
I get this 422 result:
```
{
    "error": {
        "code": "ValidationFailed",
        "message": "Validation error.",
        "details": {
            "errors": {
                "question2": [
                    "Please provide a valid value for Question2"
                ]
            }
        }
    }
}
```

Expected behaviour:
The condition to show Question2 evaluates to true because question1 has been answered with 'Yes'.
The field is mandatory so the post should result in a 422 like when email validation fails.

Other workarounds I tried:
- Add a regex validation to check if the field contains at least 1 character
- Use different data-types

**Comment by sitereactor** [comment]
Will probably need some insight from @AndyButland on this one. Maybe we need to be doing something dfferently for the validation handling for Forms in Heartcore. If for nothing else it would be interesting to hear how this is handled in the upcoming (new) api for Forms.

**Comment by AndyButland** [comment]
I've had a look into this.  When validating mandatory fields, Umbraco Forms will not consider them invalid if the field is hidden due to a condition.  So what's going wrong here is that the mandatory field is being considered as hidden due to conditions, even though it shouldn't be, as the condition - of `question1 = Yes`, is being met.

This works with a "traditional" form post in Umbraco Forms as expected, but I see the same behaviour in the new Forms API I'm working on (which is modelled on the Heartcore one).

The difference I can see is that for the usual processing, there's a step to populate the fields of `Form` object with the values posted from the submitted form.  We don't have that step in the Heartcore/Forms API processing, and as such when the check to see "is this field valid for the current conditions" is made, the value being checked against is "" rather than "Yes".  And hence it is considered as not shown and therefore correct to not validate the mandatory field is provided.

I've added that to the Forms API I'm working on and it then works as expected.  Will see about doing a PR to the Heartcore project.

**Comment by AndyButland** [comment]
PR has been created.

**Comment by sitereactor** [comment]
The fix will be part of the next update roll-out scheduled for September 28th

**Comment by sitereactor** [comment]
Closing this issue as fixed
