### ISSUE TITLE
Media publish/unpublish/scheduled publish

### ISSUE THREAD

**Issue by thonaj** [umbraco/Umbraco.Heartcore.Issues#39]
### Issue description

A use case has come up where uploading media items and publishing either after review or at a later date/scheduled release date would be the desirable work flow. Also, the ability to do the opposite, which is to unpublish/schedule unpublish to make a current media item no longer available without removing it completely. Currently these type of actions are not possible in Heartcore. It is also not possible to add Umbraco extensions to Heartcore so there are no workarounds.  After bringing up the issue with Umbraco support I was directed here.

As an additional note. It is worth mentioning that this workflow is desirable because bad actors are trying to brute force certain types of media items that have to legally be deployed and available on a strict schedule. These bad actors are trying to gain access to these media items ahead of schedule.

**Comment by sitereactor** [comment]
We don't have a publish/unpublish option for Media unfortunately, but one related area we are looking into, is being able to protect media. The idea would be that media can be protected by default similar to how its done with the Content Delivery API.
In order to access the media files you would then have to supply a token or an api key via a query string to get access to it.
It's still in a very early stage, but would be interesting to hear if this would work for your scenario?

**Comment by jmf-umbraco** [comment]
Apologies this has not received attention in some time, but unfortunately we have no further plans to do anything about it for the forseeable future.

While media items are indeed all public, the URLs have sufficient entropy that they should not realisitically be guessable.
