### ISSUE TITLE
Content notifications feature is visible but cannot be configured in Heartcore.

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Heartcore.Issues#42]
### Issue description

This - https://our.umbraco.com/documentation/tutorials/Editors-Manual/Tips-and-Tricks/Notifications/ - cannot be configured in Heartcore since you need to add SMTP settings.

The docs state the following:
![image](https://user-images.githubusercontent.com/56826332/154529024-90e75d02-1109-47dd-8a11-7d6d17052eb3.png)

Yet the feature is visible. It's a bit confusing, so the feature should either be disabled or there should be an option to add your own SMTP settings :)

**Comment by sitereactor** [comment]
This has been rolled out today, and should work for all new and existing Heartcore projects. So will close this issue.
I'm working on getting a release notes page up and running for Heartcore, so that it would be possible to link to a few more details. Still a work in progress, but let me know if you want/need more details.
