### ISSUE TITLE
Heartcore - not possible to create folders in Umbraco Forms

### ISSUE THREAD

**Issue by miguelcrpinto** [umbraco/Umbraco.Heartcore.Issues#43]
### Issue description

In the "regular Umbraco" it is possible [organize the Umbraco forms in folders](https://our.umbraco.com/documentation/add-ons/umbracoforms/Editor/Creating-a-Form/#organizing-forms-in-folders) but this option doesn't seem to be available in Heartcore. 

Is there a special reason for this to be disabled in Heartcore? Would it be possible to enable this any time soon?

**Comment by jmf-umbraco** [comment]
Hi there,

Apologies it's been some time since the last communication on this, but we're happy to inform that this is now supported for all projects created on or after February 12th this year.

We're working to roll out the feature to all older projects and we expect that it will be available for those some time in Q2.
