### ISSUE TITLE
Feature Request | CMS Workflow & Notifications

### ISSUE THREAD

**Issue by mgolubovic25** [umbraco/Umbraco.Heartcore.Issues#50]
### Issue description

On Heartcore, it is not possible for project members to configure the SMTP settings for the Workflows in CMS. 

This change can be done in the Web. config of the project only by the support team and it would be great if project members can also have this option enabled because this CMS feature is really important for us on the project. 

We were also told that each upgrade will cause workflows to fail potentially because settings will be removed so Support would need to add them back again. 

Kind regards, 
Marina

**Comment by sitereactor** [comment]
Hi @mgolubovic25 we actually just shipped this yesterday. You can see it mentioned in the Cloud update, which was just published: https://umbraco.com/blog/umbraco-product-update-march-30-2022/

So you should now be able to set up the notifications you want to receive and they will be sent out through the system without the need to configure SMTP settings 😄 

So I'll close this feature request with an "its already released"

**Comment by mgolubovic25** [comment]
Thanks, @sitereactor for the explanation. If I can ask you one more question. :) 

Does this mean that Notifications are linked to the specific User in CMS, and we can not set up some User Group (Approvers for example) and add users to it, so they all can receive notifications at once? 

Kind regards, 
Marina

**Comment by sitereactor** [comment]
Yes, Content Notifications are linked to users and cannot be set on a User Group.
User groups are for permissions, so the users would have to go in and "subscribe" to a specific type of notification in the Content section in order to receive them.

In Umbraco its a relatively basic feature, which can be configured as follows:
- a group of editors doesn't have permission to 'Publish', but does have access to 'Send to Publish'
- another group of editors have permissions to 'Publish'
- each user in the second group would have to subscribe to 'Send to Publish' in the Content section
- when an editor in the first group uses 'Send to Publish', the subscribers would receive a notification and can go in and publish the content item

Does this make sense? and more importantly align with what you wanted to archieve?

**Comment by mgolubovic25** [comment]
Hi Morten, yes, that is exactly what we want to achieve. 

Having Content Notifications linked to User Group would save us some time where we would subscribe the whole user group to a specific type of notification and not each user separately and that's the only reason I wanted to confirm things with you. 

The workflow you explained is clear and we will use it like that. :) 

Thanks for the help. 

Kind regards, 
Marina

**Comment by mgolubovic25** [comment]
Hi @sitereactor  if I can ask you one more question. 

In the case where we have a few users that can approve content for publishing, is there a way for users to receive information when someone else approves content so they are aware of it? 

Kind regards, 
Marina
