### ISSUE TITLE
Filtering of content in webhook.

### ISSUE THREAD

**Issue by jkristensen** [umbraco/Umbraco.Heartcore.Issues#51]
### Issue description

It would be a nice addition to umbraci heartcores webhooks, if it was possible to filter which if any content is sent through the webhook.

In projects that fetches and builds content using server side rendering and umbracos cdn, the relatively large json object from the webhook is not relevant.

**Comment by jmf-umbraco** [comment]
Hi @jkristensen,

Apologies for the long delay on a response to this. Unfortunately this is not something that we have heard a strong use-case for from our customers and as such we don't intend to develop this capability.

Of course, if you can let us know of a strong use-case that you think is generalisable to other customers, we would be happy to re-evaluate. Otherwise, closing this issue for now.
