### ISSUE TITLE
Allow filtering for complex types on GraphQL API

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco.Heartcore.Issues#56]
Hi,

I have been playing around with the Heartcore GraphQL API and I feel one of the features it lacks is to allow filtering by complex types like MNTP, Content Picker, etc. The only workaround at the moment is to filter it out on the client-side which is not ideal at all. I am looking at integrating a Blazor SPA with Heartcore and for me, GraphQL means a totally fluid way of querying and retrieving data. While this might not pose a major issue with websites, instances, where Heartcore is purely a content hub for relational data and the client, is a 360-degree view of that data, this can pose a real problem for the developers.

Poornima

**Comment by sitereactor** [comment]
This feature (initially supporting the MNTP) is part of our current sprint, so in about two weeks we should have an update on the progress.

**Comment by grakify90** [comment]
That's great to hear, thanks!!

**Comment by sitereactor** [comment]
Just a quick update to say that we currently have it working for "simple complex" types (Content Picker) with a query like this:
```graphql
{
  byAuthorName: allPost(
    where: { author: { OR: [{ name: "Morten" }, { name: "Rasmus" }] } }
  ) {
    edges {
      node {
        name
      }
    }
  }
}
```

There is still some way to go, as we have to update our [JoinMonster](https://github.com/umbraco/join-monster-dotnet) library to support the underlying sql generation. So we haven't deployed any updates to Production yet.
The work is currently paused due to summer vacation, but we will pick it up again in August.

**Comment by sitereactor** [comment]
We expect this to be released within a week or so. 
We are currently deploying updates and working on documentation. Once the docs have been updated I'll post back here with details.

**Comment by sitereactor** [comment]
Hi all, 

I'm closing this issue, because it is now possible to filter using complex types like the Content Picker, Media Picker and Multinode Tree Picker.

The filtering option has been updated in the documentation to reflect this:
- https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/#content-picker
- https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/#media-picker
- https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/#multinode-treepicker

and we have added a simple example to the Filtering section of the GraphQL filtering and ordering docs: https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/#using-filters

> Filtering can also be applied to types returning Content and Media, e.g. if we want all content of type Post where the author name is Rasmus, we can write the following query.
```
query {
  allPosts(where: { author: { name: "Rasmus" } }) {
    edges {
      node {
        name
        url
      }
    }
  }
}
```
