### ISSUE TITLE
Heartcore API to trigger a content transfer between environments.

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#65]
### Issue description

Hi,

We doing to some automatic content creating through the .net client, atm it is not possible for us to create the same content node on all of our 3 environments. For us to be able to have the same content node on all our environments, we need to:

1.  Create the content through api on development.
2. Manually do a content transfer between development and staging.
3. Manually do a content transfer between staging and live.

There is a "hacky" way to solve this problem by using the internal api the heartcore interface is using, but you have previously recommended that we don't use them, as they aren't intended to be used in that way.

**Comment by sitereactor** [comment]
Can you elaborate a little bit on the scenario here? Is it simply to keep the 3 environments in-sync with the same content or is there another need for automation in play here?

In a typical workflow, Editors would create content in the Live environment and Developers can pull down the content into Staging and Development as they see fit.
Some choose to use the Staging environment for creating content when there is a bigger need for approval flows - once verified the content is transfered to Live where it will then be public. Developers will pull down content into the Development environment as tey see fit and as the need arises.

**Comment by Hanskrogh** [comment]
A scenario here:

We have an external PIM system that we want to integrate with umbraco heartcore. We would like to keep our umbraco heartcore product documents synced with our PIM. When CRUD operations are done in our PIM, we need to sync with umbraco to keep content fresh.

When a product is created in our PIM, we would like to create it in all of our environments through the API's and then we need to store a reference to that document (Guid ID) in our PIM of the umbraco, so that in the future if that product is changed/deleted, it is easy for us to change/delete the document in umbraco. 

One of our initial approaches was to create the document on one the environments and then get the document ID back and then create it again in the two other environments with the same ID. The problem is that we're not allowed to specify the ID of documents created through API (the property is ignored). So the only way to keep the exact same document on all three environments is to create it on one of the environments and then transfer it afterwards through the interface.

**Comment by sitereactor** [comment]
Instead of putting all the PIM data/references into Umbraco, have you considered using an external data list editor in Umbraco, so the editors can pick products from within Umbraco?

**Comment by Hanskrogh** [comment]
Hi Morten,

I didnt knew that there was an external data list editor, this looks perfect for our use-case!!

Thank you.

**Comment by davemanton** [comment]
I'd like to suggest this as a feature too

We use Umbraco which through webhooks we add external content into our own database for speed and reliability.  As part of our CI/CD pipelines we deploy code which takes advantage of content as it is published

We may have content associated to a particular piece of code and it would be useful to be able to programmatically trigger content transfer from one environment to another as part of our deployment pipelines so the content moves as the code does

It would also be useful to be able to programmatically restore content down environments.  This would be particularly useful for us so that we could synchronise our development environment with our production environment.  This is because our marketing department will frequently create new promotions or blogs or other general page content.  If there is an issue with this content then we prefer to investigate this in our non-production environments

It is also generally useful to be able to keep our development environment in sync with our production environment so developers are generally aware of the sort of content which is being created and changed

**Comment by jmf-umbraco** [comment]
We considered adding this as a feature to Heartcore, but unfortunately have decided not to take action on it at this time.

Content transfer is a complex process that can require human intervention at many points - for example if the schema in each environment is even slightly misalinged then the process will fail. Additionally, given that content transfer can be a long-running process, the API would need to be asynchronous and include a callback mechanism or support polling etc. and we think that this is a dispoproptionate amount of effort for the value it provides.

However, there is an initiative that may go a way towards filling this need. Specifically, Umbraco Deploy (the package behind the content transfer feature) has added support for [exporting and importing content/schema packages](https://docs.umbraco.com/umbraco-deploy/deployment-workflow/import-export). While this does not currently have a convenient API, with the new back-office coming in Umbraco 14 later this year the import/export feature will need to have a standard RESTful API that you could likely use.

As such, I am closing this card for now. Thanks!
