### ISSUE TITLE
Empty Datetime field returns not null/empty value

### ISSUE THREAD

**Issue by fjprado** [umbraco/Umbraco.Heartcore.Issues#70]
### Issue description

We're experiencing the following issue with our Umbraco heartcore solution:

We have an optional field with Date/Time type. 
When this field is empty and we try to get it using GraphQL (graphql.umbraco.io) or CDN API (cdn.umbraco.io) the response is: "0001-01-01T00:00:00Z".

**Content:**
![Course Content](https://user-images.githubusercontent.com/4109319/191080454-a8c6c5cc-e972-479f-9e63-f252ff61d08d.png)

**GraphQL query and result:**
![GraphQL API](https://user-images.githubusercontent.com/4109319/191080563-8c3d1f87-4182-493d-a56f-29b483b4036e.png)

**CDN API and result:**
![CDN Api](https://user-images.githubusercontent.com/4109319/191080617-57a61661-992a-4f0d-a9de-dc97a132060b.png)

Is this the correct behaviour or could we have a different response since this field is optional?

**Comment by sitereactor** [comment]
One part of this is that the Core CMS returns DateTime Minimum Value by default, so we'd have to make another DateTime property editor for the CMS in order to change this. If we change the default it would be a breaking change.
We will consider the default behaviour for the next iteration of the REST API, and whether we should introdue another property editor, which doesn't have a minimum value like the current one.

**Comment by jmf-umbraco** [comment]
Sorry it's been some time since this had any attention, but unfortunately we do not intend to do anything further about it at this time.
