### ISSUE TITLE
Media focal points always return the same value

### ISSUE THREAD

**Issue by rajravat** [umbraco/Umbraco.Heartcore.Issues#75]
### Issue description

Focal points via the API always seem to return the same values.

1. Add an image to the media library and change the focus point for the image.
2. Add an image picker to a document type, and choose the image where you have changed the focus point.
3. Use the GraphQL API to retrieve the focal points from the image, something like this:
 `  focalPoint {
        left 
        top
      }`

The values _always_ come back as 0.5 / 0.5, regardless of what the focus points are set to for the image.

This feature would make some of the UI work we are doing around cropping images for responsive designs much easier to do if it worked. We are currently having to provide an additional data type for the user to manually put in focus points for us to consume as a workaround.

Thanks

**Comment by sitereactor** [comment]
I had a look at this and can see that we always (or only) output 0.5/0.5 by default when no Focal Point exists. Meaning that if the Image Cropper itself does not have a focal point set (selected) then it would default to 0.5/0.5-

**Comment by rajravat** [comment]
When focal points are set to media via the media library, do these not count as focal points being set? If not, what is the purpose of being able to set them for images in the media library?

**Comment by rajravat** [comment]
![image](https://user-images.githubusercontent.com/25839791/204256382-5589c776-7936-4f80-a21a-8f9aaa566036.png)

The control is Umbraco.MediaPicker3

**Comment by sitereactor** [comment]
In Media Picker v3 you have access to 2 layers of crops - on the media item itself and on the selected media on the content item. So the reason why you are getting 0.5/0.5 here is because the crop is not set in the Media Picker on the content - this means you would need to go to the media item specifically to get the "general crops" set for the image cropper.

So if you are using the REST API you would get the Content, find the media (selected with Media Picker v3) and do a look up against the media item by its Id in order to get the Crops defined on the Media item (image cropper).

Alternatively, you select a crop on the selected media on the content item.

We know its a bit confusing and we have sent this feedback to the Core CMS team in hopes we can improve it.

**Comment by sitereactor** [comment]
_This reply would probably benefit from a short recording showing the different layers of crops_
