### ISSUE TITLE
PATCH for Content Management API

### ISSUE THREAD

**Issue by rhealefever** [umbraco/Umbraco.Heartcore.Issues#8]
Currently, when wanting to update content programmatically, we send a PUT request, but any properties with existing content will be empty if the property is left empty in the request, overwriting anything that was there.

A PATCH request would solve this, but currently not possible in Heartcore.

**Comment by sitereactor** [comment]
Under consideration for version 2 of the Management API available for Umbraco Heartcore

**Comment by jmf-umbraco** [comment]
I know it's been quite some time since there was an update on this issue, but our current plan is to adopt the new backoffice management API that will be part of the core CMS in version 14.

While we understand that this won't have extensive support for PATCH operations, it will have some significant usability improvements compared to the current management API. In particular, for multi-lingual sites it will no longer be necessary to specify properties for cultures that are not being updated.

Since we'll be cutting over to that API wholesale and deprecating the current management API, I am closing this issue.
