### ISSUE TITLE
Better error message upon failed HeartCore Management Rest Api call

### ISSUE THREAD

**Issue by wvankesteren-ax** [umbraco/Umbraco.Heartcore.Issues#80]
### Issue description

Using Umbraco.Headless.Client.Net we are having issues when using the HeartCore Management REST Api (querying, updating, etc.).
In any case the api request simply returns error 500 without any additional information what's going wrong.

Please add as much as possible info about the error into the failed api request.

Looking at the umbraco's logs (through backend or Development enviroment) there could be several causes, like

- System.OutOfMemoryException
- System.NullReferenceException: PublishedSnapshotService
- System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   - more info could involve the name and value of the node and property in question
- in case a value does not reflect the datatype as defined in the document type, (e.g. storing an int into a string field)
- etc.

Note: The same was reported firstly in https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/58, however it was advised to raise a separate issue for the Managemeng API. Well,... here you are!

**Comment by jmf-umbraco** [comment]
Hi @wvankesteren-ax,

Thanks for your report. We understand that getting an error 500 with no further details can be a little frustrating.

We've recently done some work on the Management API that includes some better validation for **_some_** endpoints, so that instead of receiving an error 500, you should receive a more specific message - in some cases with validation messages regarding your inputs.

However in other cases it is valid for the server to return a 500 error response. In those cases we prefer not to leak internal implementation details to the applications on the receiving end, so it is by design that there is minimal information in the response. If you continue seeing these errors, as you identified the logs can be a means to diagnose what is going wrong.

**Comment by wvankesteren-ax** [comment]
Many thanx!

"the logs can be a means to diagnose what is going wrong" is fine!
