### ISSUE TITLE
Feature request : Bulk adding prevalues for dropdown data Types

### ISSUE THREAD

**Issue by fdwizz** [umbraco/Umbraco.Heartcore.Issues#95]
### Issue description

The current UX for adding prevalues to a list of values (for Data Types : Checkbox list, Dropdown and Radio Button List) is cumbersome. I wish this worked just as Forms prevalues : 

- possibility to bulk upload from an external source (file / Umbraco Documents / etc.) 
- possibility to have distinct Label (in the admin) and Value (in the API) : to be allowed to handle translation / automation on the frontend while keeping things verbose in the admin. 

At least being able to paste a multi-line text that would be automatically breakdown to multiple values, would be a huge time winning feature. 

I'll be available for further explanations if needed. 

thanks for considering

**Comment by jmf-umbraco** [comment]
Hi @fdwizz, thanks for your suggestion.

The intention for dropdown and radio fields is to have only a handful of items, which is why these data types are poorly suited to creating very large numbers of options.

Perhaps your property would be better suited as a Contentment Data List?

Otherwise, sometime next year when Umbraco v14 is released Heartcore will shortly thereafter adopt its new management API. That API should fully support editing prevalues via whatever client mechanism you implement.
