### ISSUE TITLE
Preview of vary-by-culture content not working

### ISSUE THREAD

**Issue by cornehoskam** [umbraco/Umbraco.Heartcore.Issues#99]
### Issue description

Hi Umbraco HQ,

While configuring the Preview URL on one of our first Heartcore project, we are running into the issue that the Preview URL functionality doesn't seem to work on content that is set to Allow vary by culture. Only content items that aren't allowed to vary have the Preview button show up when it's a descendant of an Preview URL enabled node, while our expected behaviour is that all child nodes have the preview option available. Is this a known issue?

Kind regards,
Corné

_Side note: The platform currently only has 1 language, but is being configured to have the option to be multi-lingual in the future, which is why we take the vary-by-culture into account at the initial start of this project. Might be part of the issue from a technical POV?_

**Comment by jmf-umbraco** [comment]
Hi @cornehoskam - thanks for your suggestion and apologies for the delayed response!

We'll have a look into this one and see if we can reproduce. We would like to resolve this if so, but unfortunately it's going to be early next year before we can release a fix.

**Comment by jmf-umbraco** [comment]
We are happy to inform you that we have identified and resolved this issue. Unfortunately we have been forced to batch it with an ongoing dependency upgrade of the core CMS.

We will be rolling out this dependency upgrade for new Heartcore sites in either December or January, whereas existing sites will get it slightly later - most likely before end of Q1 2024.

We'll update this issue once the fix is live on all sites.

**Comment by jmf-umbraco** [comment]
We've just rolled out a version of Heartcore that fixes this issue for all sites created after 12th February 2024. Existing sites will have this rolled out in Q2 this year.
